DROP TABLE IF EXISTS alunos;
DROP TABLE IF EXISTS cursos;

CREATE TABLE cursos (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome_curso  VARCHAR(120) NOT NULL
);

CREATE TABLE alunos (
  id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome      VARCHAR(120) NOT NULL,
  email     VARCHAR(150) NOT NULL UNIQUE,
  curso_id  INTEGER NOT NULL,
  CONSTRAINT alunos_curso_fk
    FOREIGN KEY (curso_id)
    REFERENCES cursos (id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
);

INSERT INTO cursos (nome_curso) VALUES
  ('Frontend Essentials'),
  ('Data Analytics'),
  ('Cloud & Containers');

SELECT * FROM cursos ORDER BY id;

INSERT INTO alunos (nome, email, curso_id) VALUES
  ('Aline Duarte',  'aline.duarte@gmail.com', 1),
  ('Tiago Gomides',  'gomidestiago@outlook.com', 1),
  ('Clara Nogueira','clara_1nogueira@hotmail.com',3),
  ('Diego Moreira', 'diego.moreira1@gmail.com', 2);

SELECT * FROM alunos ORDER BY id;

INSERT INTO alunos (nome, email, curso_id)VALUES 
('Ana Luiza',  'luiza.ana123@gmail.com', 10),
('Erick Moreira',  'erick.moreira@outlook.com', 7),

SELECT * FROM alunos ORDER BY id;
